### ISSUE TITLE
SQLite deployment is ephemeral

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/uploader_arweave#58]
We are currently using an ephemeral deployment of SQLite as the database. This is far from ideal as it means it is likely that data will periodically be lost. 

Potential solution: 
- Swap to MariaDB (which is already used by the Filecoin microservice)
- Alternatively: find a way to host SQLite in persistent storage.

**Comment by jamiehewitt15** [comment]
After chatting with @alexcos20 the decision is to go with a permanent deployment of SQLite

**Comment by md00ux** [comment]
Can we move the SQLite database file to a separate directory?
Currently the file **db** is in the same directory with other app. files:

```shell
root@dbs-arweave-59966ff448-688k4:/usr/src/app# pwd
/usr/src/app
root@dbs-arweave-59966ff448-688k4:/usr/src/app# ls
Dockerfile  LICENSE  README.md  app  db  estimateGas_output.txt  node_modules  package-lock.json  package.json  scripts  server.js  test
root@dbs-arweave-59966ff448-688k4:/usr/src/app# file db
db: SQLite 3.x database, last written using SQLite version 3039001
root@dbs-arweave-59966ff448-688k4:/usr/src/app# 
```

**Comment by md00ux** [comment]
Fixed using the following steps:

-create a PVC and specify  `mountPath` (eg. `/storage`) in deployment

```yaml
volumeMounts:
- mountPath: /storage
  name: sqlite-storage
```

-set the `SQLITE_DB_PATH` value to /storage/<database name> (eg. `/storage/db.sqlite3` ) in deployment

```yaml
- name: SQLITE_DB_PATH
  value: /storage/db.sqlite3
```



Confirmed that SQLite database is stored on `/storage` mountpoint:

```shell
root@uploader-arweave-78bffb498f-2vj9h:/usr/src/app# df -kh
Filesystem      Size  Used Avail Use% Mounted on
overlay          95G  6.7G   88G   8% /
tmpfs            64M     0   64M   0% /dev
/dev/sdb        974M   52K  958M   1% /storage
/dev/sda1        95G  6.7G   88G   8% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs           700M   12K  700M   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs           7.9G     0  7.9G   0% /proc/acpi
tmpfs           7.9G     0  7.9G   0% /proc/scsi
tmpfs           7.9G     0  7.9G   0% /sys/firmware
root@uploader-arweave-78bffb498f-2vj9h:/usr/src/app# ls /storage
db.sqlite3  lost+found
root@uploader-arweave-78bffb498f-2vj9h:/usr/src/app#
```

**Comment by jamiehewitt15** [comment]
ok great, thank you @md00ux. Can we close this issue then?

**Comment by md00ux** [comment]
yes, closing this issue.
